export const ISLAND_CATALOG = [
  {
    href: "/vault",
    emoji: "📸",
    title: "The Vault",
    blurb: "Private canvas-only photo stream.",
    accent: "rgba(31, 111, 84, 0.35)",
  },
  {
    href: "/games",
    emoji: "🍹",
    title: "Sip Roulette",
    blurb: "Lobbies, dares, and spin-the-wheel chaos.",
    accent: "rgba(163, 59, 43, 0.3)",
  },
  {
    href: "/fun/drinks",
    emoji: "📖",
    title: "Bar Bible",
    blurb: "No-equipment bachelor pours.",
    accent: "rgba(154, 103, 0, 0.28)",
  },
  {
    href: "/fun/snacks",
    emoji: "🍿",
    title: "Snack Tracker",
    blurb: "Tap-happy counter for the munch pile.",
    accent: "rgba(240, 194, 122, 0.45)",
  },
  {
    href: "/fun/tabs",
    emoji: "🧾",
    title: "Splitzy",
    blurb: "Settle debts in the fewest transfers.",
    accent: "rgba(126, 184, 201, 0.4)",
  },
  {
    href: "/leaderboard",
    emoji: "🏆",
    title: "The Board",
    blurb: "Circle Currency + event superlatives.",
    accent: "rgba(31, 111, 84, 0.4)",
  },
  {
    href: "/fun/gifs",
    emoji: "🎥",
    title: "GIF Wall",
    blurb: "Pin reaction GIFs like a corkboard.",
    accent: "rgba(125, 90, 160, 0.28)",
  },
  {
    href: "/fun/streaks",
    emoji: "🔥",
    title: "Streaks",
    blurb: "Days the circle actually showed up.",
    accent: "rgba(163, 59, 43, 0.35)",
  },
  {
    href: "/fun/confessions",
    emoji: "🎭",
    title: "Confess",
    blurb: "Anonymous wall. Emoji reactions only.",
    accent: "rgba(20, 32, 27, 0.25)",
  },
  {
    href: "/fun/vibe-check",
    emoji: "🌡️",
    title: "Vibe Check",
    blurb: "One-tap mood rings around avatars.",
    accent: "rgba(62, 143, 122, 0.35)",
  },
  {
    href: "/fun/most-likely",
    emoji: "🎯",
    title: "Most Likely",
    blurb: "Swipe-vote polls → Circle Legends.",
    accent: "rgba(31, 111, 84, 0.3)",
  },
  {
    href: "/fun/truth-or-dare",
    emoji: "🃏",
    title: "Truth or Dare",
    blurb: "Swipeable deck with custom dares.",
    accent: "rgba(154, 103, 0, 0.3)",
  },
  {
    href: "/fun/roulette",
    emoji: "🎰",
    title: "Sip Wheel",
    blurb: "Spin for the next dare challenge.",
    accent: "rgba(163, 59, 43, 0.32)",
  },
  {
    href: "/fun/recovery",
    emoji: "💧",
    title: "Hydration Nudge",
    blurb: "Morning-after recovery planner.",
    accent: "rgba(126, 184, 201, 0.35)",
  },
  {
    href: "/fun",
    emoji: "🌀",
    title: "Circle Lab",
    blurb: "All the quirky islands in one dock.",
    accent: "rgba(31, 111, 84, 0.28)",
  },
] as const;

export const NAV_ISLANDS = [
  { href: "/dashboard", emoji: "🏝️", label: "Islands" },
  { href: "/vault", emoji: "📸", label: "The Vault" },
  { href: "/fun/tabs", emoji: "🧾", label: "Splitzy" },
  { href: "/fun/snacks", emoji: "🍿", label: "Snacks" },
  { href: "/games", emoji: "🍹", label: "Sip Roulette" },
  { href: "/fun/gifs", emoji: "🎥", label: "GIF Wall" },
  { href: "/leaderboard", emoji: "🏆", label: "The Board" },
  { href: "/fun", emoji: "🌀", label: "Circle Lab" },
  { href: "/settings", emoji: "⚙️", label: "Settings" },
] as const;
