export const PARTY_ISLANDS = [
  {
    href: "/vault",
    emoji: "📸",
    title: "Vault",
    blurb: "Photo booth + GIFs.",
    theme: "vault",
    accent: "#7eb8c9",
    x: 12,
    y: 18,
  },
  {
    href: "/fun/tabs",
    emoji: "💸",
    title: "Who's Broke",
    blurb: "Top G vs broke menace.",
    theme: "money",
    accent: "#3d8f7a",
    x: 58,
    y: 12,
  },
  {
    href: "/fun/bar",
    emoji: "🍺",
    title: "Bar Menu",
    blurb: "Drink tiers + recipes.",
    theme: "bar",
    accent: "#f0c27a",
    x: 78,
    y: 38,
  },
  {
    href: "/fun/flags",
    emoji: "🚩",
    title: "Flag Someone",
    blurb: "Red flags (for laughs).",
    theme: "flags",
    accent: "#c45c4a",
    x: 18,
    y: 52,
  },
  {
    href: "/games",
    emoji: "🎮",
    title: "Game Night",
    blurb: "Blackjack + lobbies.",
    theme: "games",
    accent: "#e8a87c",
    x: 48,
    y: 48,
  },
  {
    href: "/fun/lock-in",
    emoji: "⏰",
    title: "Lock In/Out",
    blurb: "Selfie check-ins.",
    theme: "lock",
    accent: "#7eb8c9",
    x: 72,
    y: 68,
  },
  {
    href: "/leaderboard",
    emoji: "🥂",
    title: "Leaderboard",
    blurb: "Titles, streaks, awards.",
    theme: "board",
    accent: "#d4af37",
    x: 28,
    y: 78,
  },
  {
    href: "/fun/snacks",
    emoji: "🍿",
    title: "Snacks",
    blurb: "Munch pile counter.",
    theme: "snacks",
    accent: "#f0c27a",
    x: 8,
    y: 32,
  },
  {
    href: "/fun/gifs",
    emoji: "🎥",
    title: "GIF Wall",
    blurb: "Reaction corkboard.",
    theme: "gifs",
    accent: "#9b7bb8",
    x: 88,
    y: 18,
  },
  {
    href: "/fun/vibe-poll",
    emoji: "🔮",
    title: "Vibe Poll",
    blurb: "Rate the vibe 1–10.",
    theme: "poll",
    accent: "#5bd8a8",
    x: 42,
    y: 22,
  },
  {
    href: "/fun/regret",
    emoji: "🧾",
    title: "Regret-o-Meter",
    blurb: "Morning-after slider.",
    theme: "regret",
    accent: "#a33b2b",
    x: 62,
    y: 82,
  },
  {
    href: "/fun/blackjack",
    emoji: "🃏",
    title: "Blackjack",
    blurb: "Hit / stand mini-game.",
    theme: "games",
    accent: "#1f6f54",
    x: 88,
    y: 58,
  },
  {
    href: "/fun",
    emoji: "🌀",
    title: "Circle Lab",
    blurb: "All the extras.",
    theme: "lab",
    accent: "#3d8f7a",
    x: 38,
    y: 62,
  },
] as const;

export type PartyTheme = (typeof PARTY_ISLANDS)[number]["theme"] | "home" | "default";

export function themeForPath(pathname: string): PartyTheme {
  if (pathname === "/dashboard" || pathname === "/") return "home";
  const hit = PARTY_ISLANDS.find(
    (island) =>
      pathname === island.href || pathname.startsWith(`${island.href}/`)
  );
  return hit?.theme ?? "default";
}
